Module CreateCMDCommand

    Public Sub cReateCellCommand(ByVal outPath As String)
        Dim fso As Object
        Dim outPutFile As Object
        fso = CreateObject("Scripting.FilesystemObject")
        outPutFile = fso.OpenTextFile(outPath, 2, 1, 0)
        outPutFile.writeline("CACLP;")
        outPutFile.writeline("IOEXP;")
        outPutFile.writeline("PLLDP;")
        outPutFile.writeline("RAEPP:ID=ALL;")
        outPutFile.writeline("RAHTP:SNT=ALL;")
        outPutFile.writeline("RLACP:CELL=ALL;")
        outPutFile.writeline("RLBAP;")
        outPutFile.writeline("RLBCP:CELL=ALL;")
        outPutFile.writeline("RLBDP:CELL=ALL;")
        outPutFile.writeline("RLCAP;")
        outPutFile.writeline("RLCDP:CELL=ALL;")
        outPutFile.writeline("RLCFP:CELL=ALL;")
        outPutFile.writeline("RLCHP:CELL=ALL;")
        outPutFile.writeline("RLCLP:CELL=ALL;")
        outPutFile.writeline("RLCPP:CELL=ALL,EXT;")
        outPutFile.writeline("RLCPP:CELL=ALL;")
        outPutFile.writeline("RLCRP:CELL=ALL;")
        outPutFile.writeline("RLCXP:CELL=ALL;")
        outPutFile.writeline("RLDCP;")
        outPutFile.writeline("RLDEP:CELL=ALL,EXT;")
        outPutFile.writeline("RLDEP:CELL=ALL;")
        outPutFile.writeline("RLDGP:CELL=ALL;")
        outPutFile.writeline("RLDHP:CELL=ALL;")
        outPutFile.writeline("RLDRP:CELL=ALL;")
        outPutFile.writeline("RLDTP:CELL=ALL;")
        outPutFile.writeline("RLGAP:CELL=ALL;")
        outPutFile.writeline("RLGRP:CELL=ALL;")
        outPutFile.writeline("RLGSP:CELL=ALL;")
        outPutFile.writeline("RLHBP;")
        outPutFile.writeline("RLHPP:CELL=ALL;")
        outPutFile.writeline("RLIHP:CELL=ALL;")
        outPutFile.writeline("RLIMP:CELL=ALL;")
        outPutFile.writeline("RLLBP;")
        outPutFile.writeline("RLLCP:CELL=ALL;")
        outPutFile.writeline("RLLDP:CELL=ALL;")
        outPutFile.writeline("RLLFP:CELL=ALL;")
        outPutFile.writeline("RLLHP:CELL=ALL,EXT;")
        outPutFile.writeline("RLLHP:CELL=ALL;")
        outPutFile.writeline("RLLLP:CELL=ALL;")
        outPutFile.writeline("RLLOP:CELL=ALL,EXT;")
        outPutFile.writeline("RLLOP:CELL=ALL;")
        outPutFile.writeline("RLLPP:CELL=ALL;")
        outPutFile.writeline("RLLSP;")
        outPutFile.writeline("RLLUP:CELL=ALL;")
        outPutFile.writeline("RLMAP;")
        outPutFile.writeline("RLMFP:CELL=ALL;")
        outPutFile.writeline("RLNRP:CELL=ALL;")
        outPutFile.writeline("RLOLP:CELL=ALL;")
        outPutFile.writeline("RLOMP;")
        outPutFile.writeline("RLPBP:CELL=ALL;")
        outPutFile.writeline("RLPCP:CELL=ALL;")
        outPutFile.writeline("RLPRP:CELL=ALL;")
        outPutFile.writeline("RLSBP:CELL=ALL;")
        outPutFile.writeline("RLSLP:CELL=ALL;")
        outPutFile.writeline("RLSMP:CELL=ALL;")
        outPutFile.writeline("RLSQP;")
        outPutFile.writeline("RLSSP:CELL=ALL;")
        outPutFile.writeline("RLSTP:CELL=ALL;")
        outPutFile.writeline("RLTYP;")
        outPutFile.writeline("RLVAP;")
        outPutFile.writeline("RLVLP;")
        outPutFile.writeline("RRGBP;")
        outPutFile.writeline("RRISP:TRAPOOL=ALL;")
        outPutFile.writeline("RRTCP:DEV=ALL;")
        outPutFile.writeline("RRTPP:TRAPOOL=ALL;")
        outPutFile.writeline("SAAEP:BLOCK=RQCD,SAE=522;")
        outPutFile.writeline("SAAEP:BLOCK=RQCD,SAE=523;")
        outPutFile.writeline("SAAEP:SAE=298;")
        outPutFile.writeline("SAAEP:SAE=299;")
        outPath = Strings.Left(outPath, InStrRev(outPath, "\"))
        outPutFile.close()
        outPutFile = Nothing
        fso = Nothing
    End Sub

    Public Sub cReateMOCommand(ByVal outPath As String)
        Dim fso As Object
        Dim outPutFile As Object
        fso = CreateObject("Scripting.FilesystemObject")
        outPutFile = fso.OpenTextFile(outPath, 2, 1, 0)
        outPutFile.writeline("DTQUP:DIP=ALL;")
        outPutFile.writeline("DTSTP:DIP=ALL;")
        outPutFile.writeline("NTCOP:SNT=ALL;")
        outPutFile.writeline("RXAPP:MOTY=RXOTG;")
        outPutFile.writeline("RXASP:MOTY=RXETG;")
        outPutFile.writeline("RXASP:MOTY=RXOTG;")
        outPutFile.writeline("RXELP:MOTY=RXERX;")
        outPutFile.writeline("RXELP:MOTY=RXETF;")
        outPutFile.writeline("RXELP:MOTY=RXETRX;")
        outPutFile.writeline("RXELP:MOTY=RXETS;")
        outPutFile.writeline("RXELP:MOTY=RXETX;")
        outPutFile.writeline("RXELP:MOTY=RXOCF;")
        outPutFile.writeline("RXELP:MOTY=RXOCON;")
        outPutFile.writeline("RXELP:MOTY=RXORX;")
        outPutFile.writeline("RXELP:MOTY=RXOTF;")
        outPutFile.writeline("RXELP:MOTY=RXOTRX;")
        outPutFile.writeline("RXELP:MOTY=RXOTS;")
        outPutFile.writeline("RXELP:MOTY=RXOTX;")
        outPutFile.writeline("RXMDP:MOTY=RXOTRX;")
        outPutFile.writeline("RXMFP:MOTY=RXOCF;")
        outPutFile.writeline("RXMFP:MOTY=RXOTRX;")
        outPutFile.writeline("RXMOP:MOTY=RXERX;")
        outPutFile.writeline("RXMOP:MOTY=RXETF;")
        outPutFile.writeline("RXMOP:MOTY=RXETG;")
        outPutFile.writeline("RXMOP:MOTY=RXETRX;")
        outPutFile.writeline("RXMOP:MOTY=RXETX;")
        outPutFile.writeline("RXMOP:MOTY=RXOCF;")
        outPutFile.writeline("RXMOP:MOTY=RXOCON;")
        outPutFile.writeline("RXMOP:MOTY=RXORX;")
        outPutFile.writeline("RXMOP:MOTY=RXOTF;")
        outPutFile.writeline("RXMOP:MOTY=RXOTG;")
        outPutFile.writeline("RXMOP:MOTY=RXOTRX;")
        outPutFile.writeline("RXMOP:MOTY=RXOTX;")
        outPutFile.writeline("RXMSP:MOTY=RXERX;")
        outPutFile.writeline("RXMSP:MOTY=RXETG;")
        outPutFile.writeline("RXMSP:MOTY=RXETRX;")
        outPutFile.writeline("RXMSP:MOTY=RXETX;")
        outPutFile.writeline("RXMSP:MOTY=RXOCF;")
        outPutFile.writeline("RXMSP:MOTY=RXORX;")
        outPutFile.writeline("RXMSP:MOTY=RXOTG;")
        outPutFile.writeline("RXMSP:MOTY=RXOTRX;")
        outPutFile.writeline("RXMSP:MOTY=RXOTX;")
        outPutFile.writeline("RXTCP:MOTY=RXETG;")
        outPutFile.writeline("RXTCP:MOTY=RXOTG;")
        outPath = Strings.Left(outPath, InStrRev(outPath, "\"))
        outPutFile.close()
        outPutFile = Nothing
        fso = Nothing
    End Sub

    Public Sub cReateMSCCommand(ByVal outPath As String)
        Dim fso As Object
        Dim outPutFile As Object
        fso = CreateObject("Scripting.FilesystemObject")
        outPutFile = fso.OpenTextFile(outPath, 2, 1, 0)
        outPutFile.writeline("HGEPP:ID=ALL;")
        outPutFile.writeline("HGLSP;")
        outPutFile.writeline("MGSVP;")
        outPutFile.writeline("SAAEP:SAE=ALL;")
        outPutFile.writeline("MGEPP:ID=ALL;")
        outPutFile.writeline("MGNMP:MSC=ALL;")
        outPutFile.writeline("MGBSP:BSC=ALL;")
        outPutFile.writeline("MGCEP:CELL=ALL;")
        outPutFile.writeline("MGOCP:CELL=ALL;")
        outPutFile.writeline("MGRLP:LAI=ALL;")
        outPutFile.writeline("MGIDP;")
        outPutFile.writeline("MGADP;")
        outPutFile.writeline("PLCDP;")
        outPutFile.writeline("PLSVP;")
        outPutFile.writeline("PLOBP;")
        outPutFile.writeline("PLEIP;")

        outPath = Strings.Left(outPath, InStrRev(outPath, "\"))
        outPutFile.close()
        outPutFile = Nothing
        fso = Nothing
    End Sub

    Public Sub cReateNDCommand(ByVal outPath As String)
        Dim fso As Object
        Dim outPutFile As Object
        fso = CreateObject("Scripting.FilesystemObject")
        outPutFile = fso.OpenTextFile(outPath, 2, 1, 0)
        outPutFile.writeline("IOEXP;")
        outPutFile.writeline("RLSTP:CELL=ALL;")
        outPutFile.writeline("RLDEP:CELL=ALL; ")
        outPutFile.writeline("RLDEP:CELL=ALL,EXT; ")
        outPutFile.writeline("RLNRP:CELL=ALL;")
        outPutFile.writeline("RLCPP:CELL=ALL;")
        outPutFile.writeline("RLCFP:CELL=ALL;")
        outPutFile.writeline("RLMFP:CELL=ALL;")
        outPutFile.writeline("RXTCP:MOTY=RXOTG;")
        outPutFile.writeline("RXMOP:MOTY=RXOTRX;")
        outPutFile.writeline("RXMFP:MOTY=RXOCF;")
        outPutFile.writeline("RXMSP:MOTY=RXOTRX;")
        outPath = Strings.Left(outPath, InStrRev(outPath, "\"))
        outPutFile.close()
        outPutFile = Nothing
        fso = Nothing
    End Sub

    Public Sub cReateCell_MOCommand(ByVal outPath As String)
        Dim fso As Object
        Dim outPutFile As Object
        fso = CreateObject("Scripting.FilesystemObject")
        outPutFile = fso.OpenTextFile(outPath, 2, 1, 0)
        outPutFile.writeline("IOEXP;")
        outPutFile.writeline("ALEXP;")
        outPutFile.writeline("ALRDP;")
        outPutFile.writeline("CACLP;")
        outPutFile.writeline("RLBAP;")
        outPutFile.writeline("RLCAP;")
        outPutFile.writeline("RLDCP;")
        outPutFile.writeline("RLHBP;")
        outPutFile.writeline("RLLBP;")
        outPutFile.writeline("RLLSP;")
        outPutFile.writeline("RLMAP;")
        outPutFile.writeline("RLOMP;")
        outPutFile.writeline("RLSQP;")
        outPutFile.writeline("RLSCP;")
        outPutFile.writeline("RLTYP;")
        outPutFile.writeline("RLVAP;")
        outPutFile.writeline("RLVLP;")
        outPutFile.writeline("RAEPP:ID=ALL;")
        outPutFile.writeline("RAHTP:SNT=ALL;")
        outPutFile.writeline("RLACP:CELL=ALL;")
        outPutFile.writeline("RLAPP:CELL=ALL;")
        outPutFile.writeline("RLBCP:CELL=ALL;")
        outPutFile.writeline("RLBDP:CELL=ALL;")
        outPutFile.writeline("RLCCP:CELL=ALL;")
        outPutFile.writeline("RLCDP:CELL=ALL;")
        outPutFile.writeline("RLCFP:CELL=ALL;")
        outPutFile.writeline("RLCHP:CELL=ALL;")
        outPutFile.writeline("RLCLP:CELL=ALL;")
        outPutFile.writeline("RLCPP:CELL=ALL,EXT;")
        outPutFile.writeline("RLCPP:CELL=ALL;")
        outPutFile.writeline("RLCRP:CELL=ALL;")
        outPutFile.writeline("RLCXP:CELL=ALL;")
        outPutFile.writeline("RLDEP:CELL=ALL,EXT;")
        outPutFile.writeline("RLDEP:CELL=ALL;")
        outPutFile.writeline("RLDGP:CELL=ALL;")
        outPutFile.writeline("RLDHP:CELL=ALL;")
        outPutFile.writeline("RLDMP:CELL=ALL;")
        outPutFile.writeline("RLDRP:CELL=ALL;")
        outPutFile.writeline("RLDTP:CELL=ALL;")
        outPutFile.writeline("RLGAP:CELL=ALL;")
        outPutFile.writeline("RLGNP:CELL=ALL;")
        outPutFile.writeline("RLGQP:CELL=ALL;")
        outPutFile.writeline("RLGRP:CELL=ALL;")
        outPutFile.writeline("RLGSP:CELL=ALL;")
        outPutFile.writeline("RLHPP:CELL=ALL;")
        outPutFile.writeline("RLIHP:CELL=ALL;")
        outPutFile.writeline("RLIMP:CELL=ALL;")
        outPutFile.writeline("RLLCP:CELL=ALL;")
        outPutFile.writeline("RLLDP:CELL=ALL;")
        outPutFile.writeline("RLLFP:CELL=ALL;")
        outPutFile.writeline("RLLHP:CELL=ALL,EXT;")
        outPutFile.writeline("RLLHP:CELL=ALL;")
        outPutFile.writeline("RLLLP:CELL=ALL;")
        outPutFile.writeline("RLLOP:CELL=ALL,EXT;")
        outPutFile.writeline("RLLOP:CELL=ALL;")
        outPutFile.writeline("RLLPP:CELL=ALL;")
        outPutFile.writeline("RLLUP:CELL=ALL;")
        outPutFile.writeline("RLMFP:CELL=ALL;")
        outPutFile.writeline("RLMQP:CELL=ALL;")
        outPutFile.writeline("RLNRP:CELL=ALL;")
        outPutFile.writeline("RLOLP:CELL=ALL;")
        outPutFile.writeline("RLPBP:CELL=ALL;")
        outPutFile.writeline("RLPCP:CELL=ALL;")
        outPutFile.writeline("RLPRP:CELL=ALL;")
        outPutFile.writeline("RLPSP:CELL=ALL;")
        outPutFile.writeline("RLSBP:CELL=ALL;")
        outPutFile.writeline("RLSLP:CELL=ALL;")
        outPutFile.writeline("RLSMP:CELL=ALL;")
        outPutFile.writeline("RLSSP:CELL=ALL;")
        outPutFile.writeline("RLSTP:CELL=ALL;")
        outPutFile.writeline("RLSUP:CELL=ALL;")
        outPutFile.writeline("RLUMP:CELL=ALL;")
        outPutFile.writeline("RXASP:MOTY=RXOTG;")
        outPutFile.writeline("RXMFP:MOTY=RXOCF;")
        outPutFile.writeline("RXMOP:MOTY=RXORX;")
        outPutFile.writeline("RXMOP:MOTY=RXOTG;")
        outPutFile.writeline("RXMOP:MOTY=RXOTRX;")
        outPutFile.writeline("RXMOP:MOTY=RXOTX;")
        outPutFile.writeline("RXMSP:MOTY=RXOTG;")
        outPutFile.writeline("RXMSP:MOTY=RXOTRX;")
        outPutFile.writeline("RXTCP:MOTY=RXOTG;")

        outPath = Strings.Left(outPath, InStrRev(outPath, "\"))
        outPutFile.close()
        outPutFile = Nothing
        fso = Nothing
    End Sub
End Module
